BEGIN TRANSACTION;
DROP TABLE IF EXISTS "Character";
CREATE TABLE IF NOT EXISTS "Character" (
	"id"	INTEGER NOT NULL,
	"name"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id" AUTOINCREMENT)
);
INSERT INTO "Character" ("id","name") VALUES (1,'lol');
INSERT INTO "Character" ("id","name") VALUES (2,'lmao');
COMMIT;
